name: fmscreen
description: A Fuzzy matching screenig engine against denial lists such as BIS Entity List.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  args: ^2.0.0
  async: ^2.10.0
  fmatch:
    git: https://github.com/Cat-sushi/fmatch.git
  html: ^0.15.1
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_secure_cookie: ^1.3.0

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0

publish_to: none